### ISSUE TITLE
Feature request - (long shot I know) ability to excecute trades from within Grail via sites APIs

### ISSUE THREAD

**Issue by pdesgrip** [smartift/grail#81] opened 2018-03-14 01:37 UTC
Sounds like a mountain of work to integrate and support but just crossed my mind, it would make it quite attractive to traders to be able to trade from within Grail itself and not open the trades on the sites.

**Comment by guytp** [comment] 2018-03-14 01:57
Duplicate of #34  and #35

**Closed as completed by guytp** 2018-03-14 01:57 UTC
